/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import coordinators.GeneralCoordinator;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import java.awt.Label;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.util.List;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;


public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
	int accountNum;
	double accountBalance;
	String accountName;
	
    public HomePage(int accountNum) {
    	
    	GeneralCoordinator gCoordinator = new GeneralCoordinator();
    	List<String> accountInfo;
        accountInfo = gCoordinator.getAccountInfo(accountNum);
        this.accountNum = Integer.parseInt(accountInfo.get(0));
        this.accountName = String.valueOf(accountInfo.get(1));
        this.accountBalance = Double.parseDouble(accountInfo.get(2));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	accountNumLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");
        
        JPanel panel = new JPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(panel, GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(panel, GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        			.addContainerGap())
        );
        
        JLabel lblAccountName = new JLabel(this.accountName);
        lblAccountName.setFont(new Font("Lucida Grande", Font.PLAIN, 18));
        
        JLabel lblNewLabel = new JLabel(String.valueOf(this.accountBalance));
        lblNewLabel.setFont(new Font("Lucida Grande", Font.BOLD, 12));
        
        textField = new JTextField();
        textField.setColumns(10);
        
        JButton btnNewButton = new JButton("DEPOSIT");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt){
        		GeneralCoordinator gCoordinator = new GeneralCoordinator();
        		if (!gCoordinator.isNumeric(textField.getText())) {
        			JOptionPane.showMessageDialog(HomePage.this, "Enter Number please only", "Error", JOptionPane.ERROR_MESSAGE);
                }
        		else {
//                	if(Integer.parseInt(lblNewLabel.getText()) >= Integer.parseInt(textField.getText()))
//                	{
//                		
//                	}
//                	else
//                	{
//                		//JOptionPane.showMessageDialog(HomePage.this, "You don't have engho", "Error", JOptionPane.ERROR_MESSAGE);
//                	}
                	int money = (int) (Double.parseDouble(textField.getText())+Double.parseDouble(lblNewLabel.getText()));
                	if (gCoordinator.depositMoney(HomePage.this.accountNum, money)) {
                        lblNewLabel.setText(String.valueOf(money));           
                		JOptionPane.showMessageDialog(HomePage.this, "Your deposit has success", "Success", JOptionPane.INFORMATION_MESSAGE);
                	}
        		}
        	}
        });
        
        JButton btnNewButton_1 = new JButton("WITHDRAW");
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		GeneralCoordinator gCoordinator = new GeneralCoordinator();
        		if (!gCoordinator.isNumeric(textField.getText())) {
        			JOptionPane.showMessageDialog(HomePage.this, "Enter Number please only", "Error", JOptionPane.ERROR_MESSAGE);
                }
        		else {
                	if((boolean) (Double.parseDouble(textField.getText())<=Double.parseDouble(lblNewLabel.getText())))
                	{
                		int money = (int) (Double.parseDouble(lblNewLabel.getText()) - Double.parseDouble(textField.getText()));
                    	if (gCoordinator.depositMoney(HomePage.this.accountNum, money)) {
                            lblNewLabel.setText(String.valueOf(money));           
                    		JOptionPane.showMessageDialog(HomePage.this, "Your withdraw has success", "Success", JOptionPane.INFORMATION_MESSAGE);
                    	}
                	}
                	else
                	{
                		JOptionPane.showMessageDialog(HomePage.this, "You don't have enough money", "Error", JOptionPane.ERROR_MESSAGE);
                	}
        		}
        	}
        });
        
        JLabel lblNewLabel_1 = new JLabel(".");
        
        textField_1 = new JTextField();
        textField_1.setColumns(10);
        
        JLabel lblNewLabel_2 = new JLabel("Account Number");
        
        JLabel lblNewLabel_3 = new JLabel("Amount");
        
        textField_2 = new JTextField();
        textField_2.setColumns(10);
        
        JButton btnNewButton_2 = new JButton("Transfer");
        btnNewButton_2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		GeneralCoordinator gCoordinator = new GeneralCoordinator();
        		if (!gCoordinator.isNumeric(textField_2.getText()) || !gCoordinator.isNumeric(textField_1.getText())) {
        			JOptionPane.showMessageDialog(HomePage.this, "Enter only number please for Account number and Amount", "Error", JOptionPane.ERROR_MESSAGE);
                }
        		else
        		{
        			if (gCoordinator.transferMoney(
        					HomePage.this.accountNum,
        					Integer.parseInt(textField_1.getText()),
        					((int)(Double.parseDouble(lblNewLabel.getText())-Integer.parseInt(textField_2.getText()))),
        					Integer.parseInt(textField_2.getText())))
        					{
        				int money = (int) (Double.parseDouble(lblNewLabel.getText()) - Double.parseDouble(textField_2.getText()));
        				lblNewLabel.setText(String.valueOf(money));
                		JOptionPane.showMessageDialog(HomePage.this, "Your transformation has success", "Success", JOptionPane.INFORMATION_MESSAGE);
                		textField_2.setText("");
                		textField_1.setText("");
        					}
        		}
        	}
        });
        GroupLayout gl_panel = new GroupLayout(panel);
        gl_panel.setHorizontalGroup(
        	gl_panel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_panel.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_panel.createSequentialGroup()
        					.addGap(6)
        					.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
        				.addComponent(lblAccountName, GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
        			.addContainerGap())
        		.addGroup(gl_panel.createSequentialGroup()
        			.addGap(127)
        			.addComponent(textField)
        			.addGap(131))
        		.addGroup(gl_panel.createSequentialGroup()
        			.addGap(91)
        			.addComponent(btnNewButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnNewButton_1, GroupLayout.PREFERRED_SIZE, 97, Short.MAX_VALUE)
        			.addGap(97))
        		.addGroup(gl_panel.createSequentialGroup()
        			.addComponent(lblNewLabel_1, GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        			.addContainerGap())
        		.addGroup(gl_panel.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        				.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNewLabel_2))
        			.addGap(12)
        			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_panel.createSequentialGroup()
        					.addGap(27)
        					.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
        				.addGroup(gl_panel.createSequentialGroup()
        					.addGap(44)
        					.addComponent(lblNewLabel_3)))
        			.addGap(18)
        			.addComponent(btnNewButton_2)
        			.addContainerGap(24, Short.MAX_VALUE))
        );
        gl_panel.setVerticalGroup(
        	gl_panel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_panel.createSequentialGroup()
        			.addGap(15)
        			.addComponent(lblAccountName)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblNewLabel)
        			.addGap(18)
        			.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(gl_panel.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnNewButton)
        				.addComponent(btnNewButton_1))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblNewLabel_1)
        			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_panel.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
        					.addGroup(gl_panel.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblNewLabel_3)
        						.addComponent(lblNewLabel_2))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(gl_panel.createParallelGroup(Alignment.BASELINE)
        						.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(37))
        				.addGroup(gl_panel.createSequentialGroup()
        					.addGap(27)
        					.addComponent(btnNewButton_2, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())))
        );
        panel.setLayout(gl_panel);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage(0).setVisible(true);
            }
        });
    }

 // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumField;
    private javax.swing.JLabel accountNumLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel joinUsLabel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JButton signInBtn;
    private javax.swing.JButton signUpBtn;
    private JTextField textField;
    private JTextField textField_1;
    private JTextField textField_2;
}
